# Generated by Django 2.1.15 on 2021-03-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_staff',
            new_name='is_staff',
        ),
    ]
